[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Hugo Peixoto <hugo.peixoto@gmail.com>"]
edition = "2018"
default-run = "day21"

[dependencies]
regex = "1.4.2"
itertools = "0.9.0"
scan_fmt = "0.2.5"
